### ISSUE TITLE
Is there a way to link straight to an event in the events page?

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymcon_web_series_website#118]
Is there a way for each card in the events page itself to get a url say if I want to link directly to Todds event?

https://pymcon.com/events/
<img width="1084" alt="image" src="https://github.com/pymc-devs/pymcon_web_series_website/assets/7213793/15fada6a-3103-4f40-8c31-e6b964ee4f2c">

Here's an example from Discourse where I can link straight to Christian's post.
https://discourse.pymc.io/t/nonetype-error-on-custom-distribution/12176/2

**Comment by purna135** [comment]
Yes, this is a nice feature to have, let me add it

**Comment by canyon289** [comment]
Looking at ricardos event same idea. Before the event happens we can link to meetup. After the event happens we can link to the youtube upload of the recording

<img width="1069" alt="image" src="https://github.com/pymc-devs/pymcon_web_series_website/assets/7213793/c4a65ed7-ff75-4fa6-8fba-0bbe6903bce3">

**Comment by purna135** [comment]
> Looking at ricardos event same idea. Before the event happens we can link to meetup. After the event happens we can link to the youtube upload of the recording

I've already included this in some PR, but I forgot to mention it here: if the event is upcoming, it will display "Register now."
https://github.com/pymc-devs/pymcon_web_series_website/blob/1d753a17d2b319c42bbab4e25894912b21165721/layouts/_default/events.html#L74-L78
