### ISSUE TITLE
Update email address once we get an official email address

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_web_series_website#12]
http://pymcon.com/contact/

Current email:  [pymconference@gmail.com](mailto:pymconference@gmail.com)

**Comment by reshamas** [comment]
@purna135 
@twiecki is in touch with NumFOCUS about this.  Probably will take another week or 2 to get the email address.

**Comment by purna135** [comment]
[pymcon@pymc-devs.org](mailto:pymcon@pymc-devs.org), This is the email address that has to be updated, right?
