### ISSUE TITLE
Sponsors page

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_web_series_website#36]
Should we add a sponsors page now, and then move the "Donation" info there?

**Comment by purna135** [comment]
We had a sponsors section https://purna135.github.io/pymcon-hugo/#pymcon_sponsors, but we decided to remove it because we had no sponsorship details. We can enable this section if we have some sponsors to display by simply changing the below line to `true`.
https://github.com/pymc-devs/pymcon_2022_website/blob/d46a85230929ef922fbd15b157cfb530f674665e/config/_default/params.toml#L15

**Comment by reshamas** [comment]
@purna135
Would you be able to help set up the Sponsors page?
1) make it visible
2) Sponsorship Option (so we have something on the web page for now)
Sponsor an online event: $1000
Benefits:
- your company logo on all social media announcements
- your company logo, name and URL on the PyMC sponsors page
- opportunity to do a 1-3 minute intro at the beginning of the online webinar (talk about your organization, any job postings, any projects you want to share, etc)
3) Contact us for custom sponsorships at: [pymcon@pymc-devs.org](mailto:pymcon@pymc-devs.org)

**Comment by OriolAbril** [comment]
> your company logo, name and URL on the PyMC sponsors page

PyMC or PyMCon?

**Comment by reshamas** [comment]
> > your company logo, name and URL on the PyMC sponsors page
> 
> PyMC or PyMCon?

I meant "PyMCon".  I updated the text in my comment. Thanks!

**Comment by purna135** [comment]
Do we require an additional page or section on our home page?

**Comment by reshamas** [comment]
> Do we require an additional page or section on our home page?

Yes!  
a) Let's put Sponsors on their own page
b) Let's add Sponsors to the header menu
c) Let's move "Contact" to the footer

**Comment by purna135** [comment]
Ok, Thank you

**Comment by reshamas** [comment]
@purna135 
Are you still able to update this page?

@canyon289 
If Purna is not available, can someone help get the Sponsors page up?

**Comment by canyon289** [comment]
of course, anyone can update the website!

**Comment by purna135** [comment]
Sorry for the delay in responding; I was away from home for a few days and was unable to focus on this. I'm working on it now and will issue a PR soon.

**Comment by purna135** [comment]
Hi @reshamas.
I've created a draft [here](https://purna135.github.io/pymcon-test/sponsors/); could you please have a look and make some suggestions for improvements?
I will remove the logos(Our Sponsors section) before I create a PR.

**Comment by reshamas** [comment]
@purna135 
I think it looks good.

I would put some static section headers:
1.  "Become a Sponsor" Add in table from google doc
2.  "2023 Sponsors" and put a blank image that says "Become a Sponsor!"
3.  "2020 Sponsors"  (here, copy sponsor images from:  https://pymc-devs.github.io/pymcon/)

**Comment by reshamas** [comment]
>>"Become a Sponsor" Add in table from google doc
not sure if we should add this now, or link to a pdf file once we finalize the prospectus.

**Comment by OriolAbril** [comment]
> I've created a draft [here](https://purna135.github.io/pymcon-test/sponsors/); could you please have a look and make some suggestions for improvements?

I think there will be tiers for sponsors, so they would need to be indicated in the sponsor page, with higher tier sponsors appearing higher up in the page.

Personally I would also remove the animation and have all sponsor logos be shown always

**Comment by purna135** [comment]
Hi @reshamas. @OriolAbril, I revised some sections based on your suggestions, which can be found [here](https://purna135.github.io/pymcon-test/sponsors/); could you kindly have a look and recommend some improvements?

**Comment by reshamas** [comment]
@purna135 Thanks for this PR. I think the tables look nice!  

My comments:
a)  For "(Contact us for custom sponsorships)", can you link directly to the "Contact" page?
b)  Where are the form messages going, which email address?  Is someone monitoring that now? I sent in a couple of test messages. 
c)  At the bottom, can we add in the "PyMCon 2020 Sponsors" and their logos in?
d)  Where it currently says "PyMCon 2020 Sponsors" at the top can we update it to "PyMCon 2023 Sponsors" and add a blank logo in that says "Sponsor PyMCon" and link that to the "Contact" page?
e) email address here is:  [pymconference@gmail.com](mailto:pymconference@gmail.com), but it should be pymcon@pymc-devs.org

**Comment by reshamas** [comment]
@purna135 
I don't have any more comments at this time. 

>We currently have four sections, but is that order good or do we need to reorganise them? I merely created a few sections by reading the documents.
We can leave the 4 sections for now.

**Comment by purna135** [comment]
Is there an external document I may link to with this button, or should I link it to our contact page?

![image](https://user-images.githubusercontent.com/42216008/205657430-152157e3-ca49-4cb6-b145-07a1f4266b2f.png)

**Comment by OriolAbril** [comment]
closed by #53
