### ISSUE TITLE
organizers

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_web_series_website#39]
Given how much @purna135 has contributed to the website:
a) website take 1 (private):  https://github.com/pymc-devs/pymcon_2022/graphs/contributors
b) website take 2 (public): https://github.com/pymc-devs/pymcon_2022_website/graphs/contributors

Does it make sense to move Purna up on the list here to "Website Lead":
https://pymcon.com/organizers/

**Comment by purna135** [comment]
Thank you very much, @reshamas. I am delighted with my current position, and I am grateful to all organizers for providing this opportunity.
