### ISSUE TITLE
Events skeleton

### ISSUE THREAD

**Issue by cluhmann** [pymc-devs/pymcon_web_series_website#57]
The events page exists but is currently empty.  We now have some preliminary content that could be used to generate a initial version of this page.  Can someone open a draft PR that includes a skeleton of the structure/table/list/content so that we can begin to populate it?  I am happy to provide content, but I am not sure about the markdown format required/expected.  Or maybe there is supposed to be some sort of `.toml` file like there is for the organizers?  I'm clueless about web stuff, but happy to add info to an existing template!

**Comment by purna135** [comment]
Can we also show the PyMCon Web Series interview videos here?

**Comment by canyon289** [comment]
Id say design a small generic card that includes

* Photo
* Title
* Date
* Subtitle

Then we can link out from this card to whatever we choose!
