### ISSUE TITLE
Headshots are not uniform across events

### ISSUE THREAD

**Issue by cluhmann** [pymc-devs/pymcon_web_series_website#69]
Dante's image appears in the lower left of the event panel, but not in the Canva-created social media card.

Sandra's image appears in the Canva-created social media card, but not in the lower left of the event panel.

![image](https://user-images.githubusercontent.com/39170995/214880027-c814aafb-44c9-4a79-a498-7dac5c258cd9.png)

**Comment by purna135** [comment]
If we have the speaker's social link, we can include that as well.

**Comment by canyon289** [comment]
Ah that one is on me for these two. Moving forward Ill need each event mentors help getting all these things together, theres a couple bits that need to be aligned
