### ISSUE TITLE
Speaker cards in Canva

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_web_series_website#76]
In case someone needs to edit the Speakers Cards, here are links. 
You can make a copy and edit it:
1. Dante: https://www.canva.com/design/DAFYNrpRtgo/oqw0Zk4aRpwIJTFhf-V26w/view?utm_content=DAFYNrpRtgo&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

2. Danh: https://www.canva.com/design/DAFaSmJVSfc/N_JqlOZhyIF-f9op18TE2w/view?utm_content=DAFaSmJVSfc&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

3. Bill: https://www.canva.com/design/DAFaShzufS0/hh9nTmNNXxPrNtHcQbdGRQ/view?utm_content=DAFaShzufS0&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

4. Sandra: https://www.canva.com/design/DAFaShi-UEM/u093Cyq1aCABZVjyfP5giw/view?utm_content=DAFaShi-UEM&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

5. Hyosub: https://www.canva.com/design/DAFaShi-UEM/u093Cyq1aCABZVjyfP5giw/view?utm_content=DAFaShi-UEM&utm_campaign=designshare&utm_medium=link&utm_source=homepage_design_menu

**Comment by canyon289** [comment]
Added to repo. Thank you
