### ISSUE TITLE
Install Welcome Bot

### ISSUE THREAD

**Issue by reshamas** [pymc-devs/pymcon_web_series_website#80]
https://github.com/behaviorbot/welcome?setup_action=request

## Instructions
https://github.com/behaviorbot/welcome?setup_action=request#usage

**Comment by mjhajharia** [comment]
wouldn't an issue template do the same?

**Comment by canyon289** [comment]
I enabled this app for pymc org. Not sure if any other config is required

**Comment by reshamas** [comment]
@BhaswatiRoy
Would you like to take this issue?

It's similar to the welcome-bot set up for the pymc-data-umbrella sprint website.

**Comment by reshamas** [comment]
REF:
https://github.com/pymc-devs/pymc-data-umbrella/pull/192

**Comment by reshamas** [comment]
@SangamSwadiK 
Would you like to take this issue?

Here is an example for reference:
https://github.com/pymc-devs/pymc-data-umbrella/pull/192

**Comment by BhaswatiRoy** [comment]
> @BhaswatiRoy Would you like to take this issue?
> 
> It's similar to the welcome-bot set up for the pymc-data-umbrella sprint website.

hello
sorry, I am a bit busy with work, so won't be able to work on this.
