### ISSUE TITLE
Ordering of past and upcoming events on Events page

### ISSUE THREAD

**Issue by cluhmann** [pymc-devs/pymcon_web_series_website#84]
Could we possibly move the past events to the bottom of the page?  Right now, the default appears to be show "All Events", which places past events at the top of the page, above any upcoming events.  This makes it seem (to me) like there are no upcoming events (because I expect to find upcoming events at the top).  Thoughts @canyon289 ?

![Untitled 1](https://user-images.githubusercontent.com/39170995/218638331-b6899871-0589-4b55-b568-8c375dc52c6c.png)

**Comment by canyon289** [comment]
Agreed. @purna135 do you know how to change do a two field sort order automatically?  `key = upcoming, order`

Otherwise we can just do this manually. I'll make the PR now

**Comment by canyon289** [comment]
Alright totally hacked it with `+=1000` trick. Good enough for now. Closing

https://github.com/pymc-devs/pymcon_web_series_website/pull/85
