### ISSUE TITLE
Text getting cutoff in event cards

### ISSUE THREAD

**Issue by canyon289** [pymc-devs/pymcon_web_series_website#91]
The text is getting cut off in the event cards. 

@purna135 any ideas of what to do about this? Here's three ideas

1. I remember you once had an expand on hover feature that was removed.
2. Non uniform card length that is "always expanded"
3. Character limit

I think 3 is probably best, wanted to get your opinion as well

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/7213793/219956134-58515427-2a99-45ce-9094-e9acc25c6674.png">

**Comment by purna135** [comment]
I think we can truncate the paragraph to make the card size uniform and add a `...read more`  link at the end of paragraph. Let me try that
